### ISSUE TITLE
Make sure chain can't be changed while filling template info in creation form 

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/monorepo#108]
Each template is chain-specific, and if the chain is changed while filling its creation form, it's highly probably that state collected up to that point becomes invalid (think for example about token addresses). So we need to decide what to do at that point. a solution could just be to check if the template exists in the switched chain too, and if not, just redirect to the homepage. Either way, the user should get some feedback.

**Comment by borisblock3007** [comment]
What if we add an error message on the step where the user has changed the network? Gnosis is not implemented by default on most wallets, so maybe 'add network' button can be helpful
<img width="676" alt="Screenshot 2023-02-28 at 17 53 26" src="https://user-images.githubusercontent.com/25454493/221833412-ac7f8fc4-94d4-496b-8ec3-fb34ccd1cc73.png">

**Comment by luzzif** [comment]
I think this could work, but at that point we need to show this at every step since the user might change network even before reaching the deploy state and the form state would be invalidated anyway. Can we design a modal that doesn't let the user do anything else besides switch to the correct network or close the creation form?
