### ISSUE TITLE
Empty state design

### ISSUE THREAD

**Issue by borisblock3007** [carrot-kpi/monorepo#112]
We need to have an empty state design if there are no campaigns to display on the connected network

**Comment by borisblock3007** [comment]
Empty state draft, does the copy looks ok? We can write something else.
<img width="679" alt="Screenshot 2023-02-21 at 16 45 21" src="https://user-images.githubusercontent.com/25454493/220309438-c10c49bf-3e10-48a4-a945-f748e7294d77.png">
<img width="669" alt="Screenshot 2023-02-21 at 16 46 43" src="https://user-images.githubusercontent.com/25454493/220309449-515c3693-caef-4d2c-b101-318cd7ce759e.png">

**Comment by luzzif** [comment]
YES PLEASE. Can you move these to the ready state on Figma?
