### ISSUE TITLE
Build a management portal for us to use

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/monorepo#427]
It would be great to build a Safe-compatible management portal for Carrot where we could act on the protocol's parameters. What I'd like to see for each network:

- A section for KPI token templates
- A section for oracle templates
- A section to promote a KPI token as featured
- A section to blacklist KPI tokens

In both these sections the ability to update the spec or upgrade a template must be supported. As a bonus, we could probably use GitHub's APIs to check how outdated compared to the development version the currently deployed template's frontends and contracts are.

**Comment by guerrap** [comment]
Addressed by using Defender.
