### ISSUE TITLE
Design preferences menu for users

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/monorepo#65]
The dapp will most likely have a few settings that will be user decided. Off the top of my head:

- Decentralization mode toggle (will disable centralized pieces of the dapp such as subgraph queries, limiting functionality but ensuring a decentralized experience)
- Dark mode
- Custom per-network RPC URLs
- Custom IPFS URLs

Potentially more as they come to mind. I think we need a design for this part.

**Comment by guerrap** [comment]
I like the wallet and settings as two separate buttons too :+1:

**Comment by Diogomartf** [comment]
yeah, maybe separating buttons would be easier for the user.

**Comment by Diogomartf** [comment]
One thing I dislike is having "built by DXdao"  here, I don't think this should be place for that branding. 

When I go to the setting I want to change something on the app, I don't want to know who built it.

I think footer is the appropriate place to do it. Or we can have a section at the bottom of the landing page.
